### ISSUE TITLE
FRAME — Contact form

### ISSUE THREAD

**Issue by janeclaireh** [iamraffe/frame-theme#1]
@iamraffe This is a bug report. Looks like we need to select a list for the Mailchimp contact form; I have a FRAME list set up. Would you like access to Mailchimp to take a peek?

<img width="1099" alt="screen shot 2017-04-11 at 11 19 10 am" src="https://cloud.githubusercontent.com/assets/27295234/24919356/00aa4fbe-1ea9-11e7-8afd-b62dc6bd1edd.png">

**Comment by iamraffe** [comment]
Sure. However, just a note, you don't need me to do this in case you'd like to change this in the future. This can be managed within the WP panel.

I think I changed it correctly, give it a try (:

**Comment by janeclaireh** [comment]
Oh okay! Cool. It works now.

**Comment by iamraffe** [comment]
Perf. Closing
